/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thursday.interfaces;

import com.thursday.business.UserDirectory;
import com.thursday.business.WorkFlow;
import com.thursday.business.identities.User;
import com.thursday.business.workflow.Task;
import com.thursday.business.workflow.WorkRequest;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHEN JIEYING
 */
public class AdminManageStaffJPanel extends javax.swing.JPanel {

    private JPanel rightPanel;
    private User user;
    private DefaultTableModel dtm;
    private final String role;

    /**
     * Creates new form AdminManageStaffJPanel
     *
     * @param rightPanel
     * @param u
     * @param role
     */
    public AdminManageStaffJPanel(JPanel rightPanel, User u, String role) {
        initComponents();
        this.rightPanel = rightPanel;
        this.user = u;
        this.dtm = (DefaultTableModel) jTable1.getModel();
        this.role = role;
        this.lblTitle.setText("Manage " + capitalizeFirstChar(role.toLowerCase())
                + " Users");
        loadTable();
    }

    private String capitalizeFirstChar(String str) {
        str = " " + str;
        char[] cs = str.toCharArray();
        for (int i = 1; i < cs.length; i++) {
            if(cs[i-1]==' '&&cs[i]!=' '){
                cs[i] -= 32;
            }
        }
        return String.valueOf(cs).trim();
    }

    private boolean deleteStaff(int tableIndex) {
        if (tableIndex < 0) {
            return false;
        }

        User u = (User) dtm.getValueAt(tableIndex, 1);
        List<WorkRequest> list = WorkFlow.getReceivedRequest(u.getUsername());
        for (WorkRequest wr : list) {
            if (!WorkFlow.getTask(wr.getTaskId()).getStatus().equals(Task.Status.FINISHED)) {
                return false;
            }
        }
        return UserDirectory.deleteUser(u);
    }

    private void loadTable(String role) {
        List<User> list = UserDirectory.getCompanyStaff(user.getCompanyName());

        dtm.setRowCount(0);

        for (User u : list) {
            if (u.getRole().equals(role)) {
                Object[] row = {
                    u.getCompanyName(),
                    u,
                    u.getFirstName(),
                    u.getLastName(),
                    u.getRole()};
                dtm.addRow(row);
            }
        }
    }

    private void loadTable() {
        loadTable(this.role);
    }

    public void refreshTable() {
        loadTable();
    }

    private void addStaffPanel() {
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        this.rightPanel.add("AddStaffJPanel", new AddStaffJPanel(rightPanel, user, role));
        layout.next(this.rightPanel);
    }

    private void editStaffPanel(int index) {
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        this.rightPanel.add("EditStaffPanel", new ManageAccountPanel((User) dtm.getValueAt(index, 1), rightPanel));
        layout.next(this.rightPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Username", "First Name", "Last Name", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addBtn.setFont(addBtn.getFont());
        addBtn.setText("+Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(deleteBtn.getFont());
        deleteBtn.setText("-Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(updateBtn.getFont());
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        refreshBtn.setFont(refreshBtn.getFont());
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        btnGoBack.setText("←");
        btnGoBack.setEnabled(false);
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        lblTitle.setText("Manage Users");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateBtn)
                        .addComponent(deleteBtn)
                        .addComponent(addBtn)
                        .addComponent(refreshBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGoBack)
                        .addComponent(lblTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if (index != -1) {
            if (JOptionPane.showConfirmDialog(this, "Are you sure to delete this user?",
                    "User Management",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
                return;
            }
            if (deleteStaff(index)) {
                JOptionPane.showMessageDialog(this, "Success", "User Deleted", JOptionPane.INFORMATION_MESSAGE);
                loadTable(role);
            } else {
                JOptionPane.showMessageDialog(this, "Failed because this user is doing her/his work.",
                        "User Management", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row",
                    "User Management", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if (index != -1) {
            editStaffPanel(index);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row",
                    "User Management", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        addStaffPanel();
    }//GEN-LAST:event_addBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        this.rightPanel.remove(this);
        layout.previous(this.rightPanel);
    }//GEN-LAST:event_btnGoBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
