/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thursday.interfaces;



import com.thursday.business.identities.AbstractUser;
import com.thursday.business.identities.ApartmentUserBiz;
import com.thursday.business.identities.CleaningCompUserBiz;
import com.thursday.business.identities.User;
import com.thursday.util.Validator;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CHEN JIEYING
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    
    private ApartmentUserBiz apBiz;
    private CleaningCompUserBiz ccBiz;

    private final MainFrame mFrame;
    private final JPanel rightPanel;
    //private User user;
    static final String TXTPSWD_HINT = "Password";
    static char defaultChar;
    private String username;
    
    public LoginJPanel(MainFrame f, ApartmentUserBiz apBiz, CleaningCompUserBiz ccBiz) {
        initComponents();
        this.mFrame = f;
        this.rightPanel = f.getRightPanel();
        this.apBiz = apBiz;
        this.ccBiz = ccBiz;
        this.username = username;
        
        ItemListener il = new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                //System.out.println(e.getSource());
                //fillUserBox();
                passwordField.setText(TXTPSWD_HINT);
                passwordField.setEchoChar('\0');
                passwordField.setForeground(Color.GRAY);
            }
        };

        this.apartmentRBtn.addItemListener(il);
        this.cleaningCompanyRBtn.addItemListener(il);
        defaultChar = this.passwordField.getEchoChar();
     //set user "Administrator" default password
        passwordField.setText("admin");

        txtPswdAddListener();
    }


    private void txtPswdAddListener() {
        passwordField.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent e) {// when focus lost
                String pswd = new String(passwordField.getPassword());
                if (pswd.equals("")) {// no password
                    passwordField.setEchoChar('\0');// plaintext
                    passwordField.setText(TXTPSWD_HINT);
                    passwordField.setForeground(Color.LIGHT_GRAY);
                }
            }

            @Override
            public void focusGained(FocusEvent e) {// when focus gained
                String pswd = new String(passwordField.getPassword());
                if (pswd.equals(TXTPSWD_HINT)) {
                    passwordField.setText("");
                    passwordField.setEchoChar(defaultChar);// ciphertext
                    passwordField.setForeground(Color.BLACK);
                }
            }
        });
    }

    private void grantAccess(User user) {
        if(apartmentRBtn.isSelected()){
            User u=ApartmentUserBiz.getUser(usernameTxt.getText());
            if(u.authenticate(passwordField.getPassword())){
                CardLayout layout = (CardLayout) this.rightPanel.getLayout();
                AdminBarJPanel panel = new AdminBarJPanel(rightPanel,user);
                this.rightPanel.add("AdminBarJPanel", panel);
                layout.next(rightPanel);
            }else{
                JOptionPane.showMessageDialog(this, "Wrong Password", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            User u=CleaningCompUserBiz.getUser(usernameTxt.getText());
            if(u.authenticate(passwordField.getPassword())){
                CardLayout layout = (CardLayout) this.rightPanel.getLayout();
                HRBarJPanel panel = new HRBarJPanel(rightPanel,user);
                this.rightPanel.add("HRBarJPanel", panel);
                layout.next(rightPanel);
            }else{
                JOptionPane.showMessageDialog(this, "Wrong Password", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        apartmentRBtn = new javax.swing.JRadioButton();
        cleaningCompanyRBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        backBtn = new javax.swing.JButton();

        jLabel1.setText("Login as:");

        buttonGroup1.add(apartmentRBtn);
        apartmentRBtn.setSelected(true);
        apartmentRBtn.setText("Apartment");

        buttonGroup1.add(cleaningCompanyRBtn);
        cleaningCompanyRBtn.setText("Cleaning company");

        jLabel3.setText("Password");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Username");

        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(passwordField))
                .addGap(419, 419, 419))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cleaningCompanyRBtn)
                            .addComponent(apartmentRBtn)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(loginBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(apartmentRBtn)
                .addGap(18, 18, 18)
                .addComponent(cleaningCompanyRBtn)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(loginBtn)
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        char[] pswd = passwordField.getPassword();
        String uname = new String(usernameTxt.getText()).trim();
        User u = ApartmentUserBiz.getUser(uname);
        
        if (Validator.IsEmpty(pswd)) {
            JOptionPane.showMessageDialog(this, "Please Enter Password", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if(Validator.IsEmpty(uname)){
            JOptionPane.showMessageDialog(this, "Please Enter Username", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if(u == null){
            JOptionPane.showMessageDialog(this, "Please Sign Up first", "WARNING", JOptionPane.WARNING_MESSAGE);         
        }else if(u.authenticate(pswd) == false){
            JOptionPane.showMessageDialog(this, "Wrong Password", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else{
            grantAccess(u);
            mFrame.setLoggedUser(u);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        this.rightPanel.remove(this);
        layout.previous(this.rightPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton apartmentRBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cleaningCompanyRBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
