/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel.interfaces;

import com.travel.business.Aircraft;
import com.travel.business.AircraftList;
import com.travel.business.FlightDirectory;
import com.travel.users.Airliner;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andy
 */
public class AirlinerManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerManagePanel
     */
    private AircraftList aircraftList;
    private JPanel bottomPanel;
    private Airliner airliner;
    private FlightDirectory flightDirectory;
    public AirlinerManagePanel(JPanel buttomPanel,AircraftList aircraftList,FlightDirectory flightDirectory, Airliner airliner) {
        initComponents();
        this.bottomPanel = buttomPanel;
        this.aircraftList = aircraftList;
        this.flightDirectory = flightDirectory;
        this.airliner = airliner;
        airlinerLabel.setText(airliner.getProviderName());
        populateTable(aircraftList.getAircraftDir());
        
    }
public void populateTable(ArrayList<Aircraft> aircraftList){
        
        DefaultTableModel dtm = (DefaultTableModel)tblAircraft.getModel();
        dtm.setRowCount(0);
        
        
        for(Aircraft aircraft : aircraftList){
            if(aircraft.getAirliner() == airliner.getProviderName()){
            Object row[] = new Object [2];
            row[0] = aircraft;
            row[1] = aircraft.getModel();
            
            dtm.addRow(row);
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAircraft = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        airlinerLabel = new javax.swing.JLabel();

        tblAircraft.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration", "Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAircraft);

        btnAdd.setText("Add New Aircraft");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Aircraft");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnManage.setText("Manage Aircraft");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Airliner:");

        airlinerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(airlinerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(airlinerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManage)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblAircraft.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Aircraft aircraft =(Aircraft)tblAircraft.getValueAt(selectedRow, 0);
                aircraftList.deleteAircraft(aircraft);
                populateTable(aircraftList.getAircraftDir());
                
            
            flightDirectory.deleteSelectedAirCraft(aircraft.getModelNum());
            
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        AddAircraftPanel addAircraftPanel = new AddAircraftPanel(bottomPanel,aircraftList,airliner);
        this.bottomPanel.add("AddAircraftPanel",addAircraftPanel);
        CardLayout cardLayout = (CardLayout)this.bottomPanel.getLayout();
        cardLayout.next(bottomPanel);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAircraft.getSelectedRow();
        if (selectedRow >= 0) {
            Aircraft aircraft = (Aircraft)tblAircraft.getValueAt(selectedRow, 0);
        String modelNum = aircraft.getModelNum();
        ManageAirCraftPanel manageAirCraftPanel = new ManageAirCraftPanel(bottomPanel, flightDirectory, aircraftList, modelNum, airliner);
        this.bottomPanel.add("ManageAirCraftPanel",manageAirCraftPanel);
        CardLayout cardlayout = (CardLayout)this.bottomPanel.getLayout();
        cardlayout.next(bottomPanel);
        } 
        else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
        

    }//GEN-LAST:event_btnManageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinerLabel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnManage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAircraft;
    // End of variables declaration//GEN-END:variables
}
