/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel.interfaces;

import com.travel.users.Airliner;
import com.travel.users.Customer;
import com.travel.users.User;
import java.awt.CardLayout;
import com.travel.business.Business;

/**
 *
 * @author lihang
 */
public class MainMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuPanel
     */
    private final User user;
    
    
    public MainMenuPanel(User u) {
        initComponents();
        this.user=u;
        //this.lblUsername.setText(u.getUsername());
        detectUserType();
    }
    
    private void detectUserType(){
        int type=user.getUserType();
        
        switch(type){
            case User.ADMINISTRATOR:
                lblUsername.setText(user.getUsername());
                btnAdmins.setEnabled(true);
                btnAirliner.setEnabled(true);
                btnCustomers.setEnabled(true);
                btnFlights.setEnabled(true);
                btnBookFlight.setEnabled(false);
                btnMyFlight.setEnabled(false);
                break;
            case User.AIRLINER:
                lblUsername.setText(((Airliner)user).getProviderName());
                btnAdmins.setEnabled(false);
                btnAirliner.setEnabled(false);
                btnCustomers.setEnabled(false);
                btnFlights.setEnabled(true);
                btnBookFlight.setEnabled(false);
                btnMyFlight.setEnabled(false);
                break;
            case User.CUSTOMER:
                lblUsername.setText(((Customer)user).getFullName());
                btnAdmins.setEnabled(false);
                btnAirliner.setEnabled(false);
                btnCustomers.setEnabled(false);
                btnFlights.setEnabled(false);
                btnBookFlight.setEnabled(true);
                btnMyFlight.setEnabled(true);
                break;
            default:
                break;
                        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        btnAdmins = new javax.swing.JButton();
        btnAirliner = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnBookFlight = new javax.swing.JButton();
        btnFlights = new javax.swing.JButton();
        btnMyFlight = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jSplitPane1.setBorder(null);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("*Username*");

        btnAdmins.setText("Manage Admins");

        btnAirliner.setText("Manage Airliners");

        btnCustomers.setText("Manage Customers");

        btnBookFlight.setText("Book A Flight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        btnFlights.setText("Manage Flights");
        btnFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightsActionPerformed(evt);
            }
        });

        btnMyFlight.setText("Manage My Flights");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdmins, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAirliner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCustomers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(btnMyFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdmins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAirliner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomers)
                    .addComponent(btnBookFlight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFlights)
                    .addComponent(btnMyFlight))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        bottomPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Click Buttons above to Continue");
        bottomPanel.add(jLabel2, "card2");

        jSplitPane1.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)this.bottomPanel.getLayout();
        SearchFlightPanel panel=new SearchFlightPanel(this.bottomPanel);
        this.bottomPanel.add(panel);
        layout.next(this.bottomPanel);
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void btnFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightsActionPerformed
        
        Airliner airliner = (Airliner) user;
        AirlinerManagePanel airlinerManagePanel = new AirlinerManagePanel(bottomPanel, Business.getInstance().getAircraftList(),Business.getInstance().getFlightDirectory(), airliner);
        this.bottomPanel.add("AirlinerManagePanel",airlinerManagePanel);
        CardLayout cardLayout = (CardLayout)this.bottomPanel.getLayout();
        cardLayout.next(bottomPanel);
        
       
    }//GEN-LAST:event_btnFlightsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnAirliner;
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnFlights;
    private javax.swing.JButton btnMyFlight;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
