/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel.interfaces;

import com.travel.business.AircraftList;
import com.travel.business.Flight;
import com.travel.business.FlightDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andy
 */
public class ManageAirCraftPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirCraftPanel
     */
    private FlightDirectory flightDirectory;
    private JPanel bottomPanel;
    private String modelNum;
    private AircraftList aircraftList;
    public ManageAirCraftPanel(JPanel bottomPanel, FlightDirectory flightDirectory,AircraftList aircraftList, String modelNum) {
        initComponents();
        this.flightDirectory = flightDirectory;
        this.bottomPanel = bottomPanel;
        this.modelNum = modelNum;
        this.aircraftList = aircraftList;
        modelNumLabel.setText(modelNum);  
        populateTable(flightDirectory.getFlightDir());
    }
    
    public void populateTable(ArrayList<Flight> flightDir){
        
        DefaultTableModel dtm = (DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        
        
        for(Flight flight : flightDir){
            if(flight.getModelNum() == modelNum){
            Object row[] = new Object [4];
            row[0] = flight;
            row[1] = flight.getDeparture();
            row[2] = flight.getArrival();
            row[3] = flight.getTakeOffTime();
            dtm.addRow(row);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlight = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCreateFlight = new javax.swing.JButton();
        btnDeleteFlight = new javax.swing.JButton();
        btnUpdateFlight = new javax.swing.JButton();
        modelNumLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        tblFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Flight Number", "From", "To", "Date & Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFlight);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Manage Aircraft:");

        btnCreateFlight.setText("Create Flight");
        btnCreateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFlightActionPerformed(evt);
            }
        });

        btnDeleteFlight.setText("Delete Flight");
        btnDeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFlightActionPerformed(evt);
            }
        });

        btnUpdateFlight.setText("View & Update Flight");
        btnUpdateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFlightActionPerformed(evt);
            }
        });

        modelNumLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        btnBack.setText("←");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnCreateFlight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteFlight)
                        .addGap(12, 12, 12)
                        .addComponent(btnUpdateFlight)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addComponent(modelNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateFlight)
                    .addComponent(btnDeleteFlight)
                    .addComponent(btnUpdateFlight))
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFlightActionPerformed
        int selectedRow = tblFlight.getSelectedRow();
        if (selectedRow >= 0) {
            
            Flight flight = (Flight)tblFlight.getValueAt(selectedRow, 0);
            ViewFlightPanel viewFlightPanel = new ViewFlightPanel(bottomPanel, flightDirectory, flight);
            this.bottomPanel.add("ViewFlightPanel",viewFlightPanel);
        CardLayout cardLayout = (CardLayout) this.bottomPanel.getLayout();
        cardLayout.next(bottomPanel); 
            
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
        
    }//GEN-LAST:event_btnUpdateFlightActionPerformed

    private void btnCreateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFlightActionPerformed
        CardLayout layout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add(new CreateFlightsPanel(bottomPanel,flightDirectory,modelNum));
        layout.next(bottomPanel);
        
    }//GEN-LAST:event_btnCreateFlightActionPerformed

    private void btnDeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFlightActionPerformed
               
        int selectedRow = tblFlight.getSelectedRow();
        
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
            Flight flight = (Flight)tblFlight.getValueAt(selectedRow, 0);
            flightDirectory.deleteFlight(flight);
            populateTable(flightDirectory.getFlightDir());
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
    }//GEN-LAST:event_btnDeleteFlightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        this.bottomPanel.remove(this);
        CardLayout cardLayout =(CardLayout)bottomPanel.getLayout();
        Component[] comps = this.bottomPanel.getComponents();
        for(Component comp : comps){
            if(comp instanceof AirlinerManagePanel){

                AirlinerManagePanel airlinerManagePanel = (AirlinerManagePanel) comp;
                airlinerManagePanel.populateTable(aircraftList.getAircraftDir());
            }
        }
        cardLayout.previous(bottomPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateFlight;
    private javax.swing.JButton btnDeleteFlight;
    private javax.swing.JButton btnUpdateFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modelNumLabel;
    private javax.swing.JTable tblFlight;
    // End of variables declaration//GEN-END:variables
}
