/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel.interfaces;

import com.travel.business.AirlinerList;
import com.travel.business.Business;
import com.travel.business.CustomerList;
import com.travel.users.Admin;
import com.travel.users.Airliner;
import com.travel.users.Customer;
import com.travel.util.Validator;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CHEN JIEYING
 */
public class UserCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private JPanel rightPanel;
    private AirlinerList airlinerList;
    private CustomerList customerList;
    private Admin admin;

    public UserCreatePanel(JPanel panelRight, AirlinerList airlinerList, CustomerList customerList) {
        initComponents();
        this.rightPanel = panelRight;
        this.airlinerList = airlinerList;
        this.customerList = customerList;
        this.admin = admin;

        this.radioAirliner.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setTxtEnabled(false);
            }

        });
        this.radioCustomer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setTxtEnabled(true);
            }

        });
    }

    private void setTxtEnabled(boolean b) {
        this.txtFirstName.setVisible(b);
        this.lblFirstName.setVisible(b);
        if (!b) {
            this.lblProviderLast.setText("Airline");

        } else {
            this.lblProviderLast.setText("Last Name");
        }

    }

    private void clearAllFields() {
        this.txtFirstName.setText("");
        this.txtProviderLast.setText("");
        this.txtPword.setText("");
        this.txtRePword.setText("");
        this.txtUser.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtProviderLast = new javax.swing.JTextField();
        txtPword = new javax.swing.JTextField();
        txtRePword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioCustomer = new javax.swing.JRadioButton();
        radioAirliner = new javax.swing.JRadioButton();
        lblProviderLast = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        txtProviderLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProviderLastActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password:");

        jLabel3.setText("Confirm");

        btnGroup.add(radioCustomer);
        radioCustomer.setSelected(true);
        radioCustomer.setText("Customer");
        radioCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCustomerActionPerformed(evt);
            }
        });

        btnGroup.add(radioAirliner);
        radioAirliner.setText("Airliner");
        radioAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAirlinerActionPerformed(evt);
            }
        });

        lblProviderLast.setText("Last Name");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        lblFirstName.setText("First Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProviderLast)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(lblFirstName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser)
                    .addComponent(txtProviderLast)
                    .addComponent(txtPword)
                    .addComponent(txtRePword)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioAirliner)
                            .addComponent(radioCustomer))
                        .addGap(0, 115, Short.MAX_VALUE))
                    .addComponent(txtFirstName))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProviderLast)
                    .addComponent(txtProviderLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRePword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(radioAirliner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCustomer)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("←");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreate)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String firstname = txtFirstName.getText().trim();
        String provider = txtProviderLast.getText();
        String username = txtUser.getText();
        String password = txtPword.getText();
        String repassword = txtRePword.getText();

        if (Validator.IsEmpty(username)) {
            txtUser.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Username can't be empty");
            return;
        }
        if (!Validator.IsUsername(username)) {
            JOptionPane.showMessageDialog(null, "Username should be in the form of Words and Number");
            txtUser.setBorder(BorderFactory.createLineBorder(Color.RED));
            return;
        }

        if (Validator.IsEmpty(provider)) {
            txtProviderLast.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Last Name/Provider Name can't be empty");
            return;
        }
//        if (!Validator.IsEmail(provider)) {
//            JOptionPane.showMessageDialog(null, "E-mail should be in the form of xxx_xxx@xxx.xxx");
//            txtProviderLast.setBorder(BorderFactory.createLineBorder(Color.RED));
//            return;
//        }

        if (Validator.IsEmpty(password)) {
            txtPword.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Password can't be empty");
            return;
        }
        if (!Validator.IsPassword(password)) {
            JOptionPane.showMessageDialog(null, "Password should be in the form of at least 6 letters and including numbers, Lowercase and Uppercase ");
            txtPword.setBorder(BorderFactory.createLineBorder(Color.RED));
            return;
        }

        if (Validator.IsEmpty(repassword)) {
            txtRePword.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Re-enter password can't be empty");
            return;
        }
        if (!Validator.IsSamePassword(password, repassword)) {
            JOptionPane.showMessageDialog(null, "Re-enter password is not as same as previous password");
            txtRePword.setBorder(BorderFactory.createLineBorder(Color.RED));
            return;
        }
        if (Business.getInstance().getAirliners().getAirliner(username) == null
                || Business.getInstance().getCustomers().getCustomer(username) == null) {
            JOptionPane.showMessageDialog(this, "Username exists!",
                    "WARNING", JOptionPane.WARNING_MESSAGE);
            txtUser.setBorder(BorderFactory.createLineBorder(Color.RED));
        } else if (radioAirliner.isSelected()) {
            Airliner a = new Airliner(username, password);
            a.setProviderName(provider);
            airlinerList.getAirlinerList().add(a);
            JOptionPane.showMessageDialog(null, "Airliner created Successfully");
            clearAllFields();
            //toMainScreen();
        } else if (radioCustomer.isSelected()) {
            Date date = new Date();
            Customer c = new Customer(username, password);
            c.setFirstName(firstname);
            c.setLastName(provider);
            customerList.getCustomerList().add(c);
            JOptionPane.showMessageDialog(null, "Customer created Successfully");
            clearAllFields();
            //toMainScreen();
        }


    }//GEN-LAST:event_btnCreateActionPerformed

    private void radioCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_radioCustomerActionPerformed

    private void radioAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAirlinerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAirlinerActionPerformed

    private void txtProviderLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProviderLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProviderLastActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        this.rightPanel.remove(this);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        cardLayout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    /*
private void toMainScreen() {
        CardLayout layout = (CardLayout) this.panelRight.getLayout();
        this.panelRight.remove(this);
        Component[] comps = this.panelRight.getComponents();
        for(Component comp: comps){
            if(comp instanceof MainMenuPanel){
                MainMenuPanel panel = (MainMenuPanel) comp;
                panel.populate();
            }
        }
        layout.previous(panelRight);
    }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblProviderLast;
    private javax.swing.JRadioButton radioAirliner;
    private javax.swing.JRadioButton radioCustomer;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtProviderLast;
    private javax.swing.JTextField txtPword;
    private javax.swing.JTextField txtRePword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
